In [45]:
#项目7-例7-1代码
#数据准备
from sklearn.datasets import load_breast_cancer #导入肺癌数据集
from sklearn.svm import SVC     #导入支持向量机分类模块
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

x,y=load_breast_cancer().data,load_breast_cancer().target 
print(x.shape)
print(x)

(569, 30)
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [46]:
#数据标准化处理
from sklearn.preprocessing import StandardScaler

x=StandardScaler().fit_transform(x)
print(x)

[[ 1.09706398 -2.07333501  1.26993369 ...  2.29607613  2.75062224
   1.93701461]
 [ 1.82982061 -0.35363241  1.68595471 ...  1.0870843  -0.24388967
   0.28118999]
 [ 1.57988811  0.45618695  1.56650313 ...  1.95500035  1.152255
   0.20139121]
 ...
 [ 0.70228425  2.0455738   0.67267578 ...  0.41406869 -1.10454895
  -0.31840916]
 [ 1.83834103  2.33645719  1.98252415 ...  2.28998549  1.91908301
   2.21963528]
 [-1.80840125  1.22179204 -1.81438851 ... -1.74506282 -0.04813821
  -0.75120669]]


In [47]:
#建立支持向量机模型
#分割数据集
from sklearn.metrics import accuracy_score

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=420)
Kernel=["linear","poly","rbf","sigmoid"] #4种核函数
for kernel in Kernel:
    model=SVC(kernel=kernel,gamma="auto",
              degree=1)#设置多项式核函数的degree参数为1
    model.fit(x_train,y_train)
    pred=model.predict(x_test)
    ac=accuracy_score(y_test,pred)
    print("选择%s核函数时，模型的预测准确率为%f"%(kernel,ac))
             

选择linear核函数时，模型的预测准确率为0.976608
选择poly核函数时，模型的预测准确率为0.964912
选择rbf核函数时，模型的预测准确率为0.970760
选择sigmoid核函数时，模型的预测准确率为0.953216
