In [7]:
#项目5-项目实施代码
#导入os模块
import os

#获取正常邮件和垃圾邮件的文件列表
normalFileList=os.listdir("../item5/item5-ss-data/normal/")
spamFileList=os.listdir("../item5/item5-ss-data/spam/")
print("正常邮件的文件列表",normalFileList)
print("垃圾邮件的文件列表",spamFileList)

#获取停用词表，用于对停用词进行过滤
stopList=[]   #存放停用词
for line in open("../item5/item5-ss-data/stopwords.txt",encoding='utf-8'):
    stopList.append(line[:len(line)-1])
print("停用词文件内容：",stopList)

正常邮件的文件列表 ['normal-mail1.txt', 'normal-mail2.txt', 'normal-mail3.txt', 'normal-mail4.txt', 'normal-mail5.txt', 'normal-mail6.txt', 'normal-mail7.txt', 'normal-mail8.txt', 'normal-mail9.txt']
垃圾邮件的文件列表 ['spam-mail1.txt', 'spam-mail2.txt', 'spam-mail3.txt', 'spam-mail4.txt', 'spam-mail5.txt', 'spam-mail6.txt', 'spam-mail7.txt', 'spam-mail8.txt', 'spam-mail9.txt']
停用词文件内容： ['啊', '阿', '哎', '哎呀', '唉', '于是', '还']


In [8]:
#导入需要的库
from jieba import cut#导入中文分词库（结巴分词）
from re import sub

#定义getWords()函数，用于提取指定文件（邮件文件）的词语
def getWords(file,stopList):
    wordsList=[]
    for line in open(file,encoding='utf-8'):
        line=line.strip() #移除字符串头尾指定的字符（默认为空格或换行符）或字符序列
        #过滤干扰字符或无效字符
        line=sub(r'[.【】0-9、——，。！\~*]','',line)  
        line=cut(line)
        #过滤长度为1的单个字
        line=filter(lambda word:len(word)>1,line) 
        wordsList.extend(line)
        #过滤停用词，剩余有效词语
        words=[]
        for i in wordsList:
            if i not in stopList and i.strip()!='' and i!=None:
                words.append(i)
    return words

In [9]:
#提取训练集所有文件中的词语与出现频次最高的前10个词语

#导入需要的库
from collections import Counter
from itertools import chain

#提取训练集所有文件中的词语
allwords=[]
for spamfile in spamFileList:
    words=getWords("../item5/item5-ss-data/spam/"+spamfile,stopList)
    allwords.append(words)
for normalfile in normalFileList:
    words=getWords("../item5/item5-ss-data/normal/"+normalfile,stopList)
    allwords.append(words)
print("训练集中所有的有效词语列表：")
print(allwords)

#提取训练集中出现频次最高的前10个词语
frep=Counter(chain(*allwords))  #获取有效词语出现的频次
topTen=frep.most_common(10)#获取出现频次最高的前10个词语和对应的频次
topWords=[w[0] for w in topTen] #获取出现频次最高的前10个词语
print("训练集中出现频次最高的前10个词语:")
print(topWords)


训练集中所有的有效词语列表：
[['期刊', '主要', '栏目', '技术', '应用', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '数据', '投稿', '邮箱', 'xx', 'com'], ['某某', '期刊', '主要', '栏目', '数据', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '计算', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '人工智能', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '网络设备', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '计算机', '基础', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '网络', '制图', '投稿', '邮箱', 'xx', 'com'], ['期刊', '主要', '栏目', '网站', '绘图', '投稿', '邮箱', 'xx', 'com'], ['张老师', '您好', '上次', '推荐', '资料', '来说', '帮助', '很大', '希望', '推荐', '一些', '资料', '非常感谢'], ['小李', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['李老师', '您好', '论文', '已经', '修改', '修改', '完成', '内容', '附件', '查收'], ['小李', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['小张', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['张老师', '您好', '论文', '修改', '具体内容', '附件', '查收'], ['李老师', '你好', '论文', '修改', '中等', '修改', '完成', '沟通'], ['小张', '你好', '论文', '需要', '修改', '具体', '修改意见', '附件', '查收'], ['小张', '你好', '

In [10]:
#获取10个高频词语在每封邮件中出现的次数
#导入需要的库
import numpy as np

vector=[]
for words in allwords:
    temp=list(map(lambda x:words.count(x),topWords)) #每个高频词语在每封邮件中出现的次数
    vector.append(temp)
vector=np.array(vector)
print("10个高频词语在每封邮件中出现的次数：")
print(vector)

10个高频词语在每封邮件中出现的次数：
[[0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 1]
 [2 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]
 [2 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 1 1]]


In [11]:
#使用朴素贝叶斯算法训练模型
from sklearn.naive_bayes import MultinomialNB

#为数据集打标签，1表示垃圾邮件，0表示正常邮件
target=np.array([1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0])
x,y=vector,target

#建立多项式朴素贝叶斯模型并进行训练
model=MultinomialNB()
model.fit(x,y)


MultinomialNB()

In [12]:
#使用模型预测新的未知邮件的类别

#获取测试邮件文件列表
test=os.listdir("../item5/item5-ss-data/test")
#使用模型进行预测
for testFile in test:
    words=getWords("../item5/item5-ss-data/test/"+testFile,stopList)#调用getWords()函数，提取文件词语
    test_x=np.array(tuple(map(lambda x:words.count(x),topWords))) #提取10个高频词语分别在邮件中出现的次数
    result=model.predict(test_x.reshape(1,-1))
    if result==1:
        print('"'+testFile+'"'+"是垃圾邮件")
    else:
         print('"'+testFile+'"'+"是正常邮件")

"normal-test.txt"是正常邮件
"spam-test.txt"是垃圾邮件
